### PR TITLE
Update __init__.py for OSX

### PR DESCRIPTION
**Pull request by sdfgsdfgd**

### CODE REVIEW

**Comment by sdfgsdfgd** [comment]
now it can be used on OSX with a code like this;

```
if platform.system() == "Darwin":
    folder_path = "./"
    chromedriver_path = download_undetected_chromedriver(folder_path, undetected=True, arm=False, force_update=True)
    driver = uc.Chrome(driver_executable_path=chromedriver_path)
```
    
`folder_path` parameter might be unnecessary, I didn't have time to check for that, it's slapping things on the `Desktop` for now... maybe you could change that to work with `folder_path` instead , I did this patch in a hurry lol. Vielen Dank

**Comment by sdfgsdfgd** [comment]
actually chmod wasn't working - I had to fix it one more time. Now it looks good. 

For some reason I couldn't make it work with `folder_path_for_exe` , for now it's working via destination folder of  ~/Desktop  

should be an easy fix but I'm not sure, weird that it didn't work (I was passing "." , the current folder as parameter to the library, and if I use the argument it just fails for some reason )

**Review by hansalemaos — APPROVED** [review]

**Comment by sdfgsdfgd** [comment]
ok I fixed the Desktop path weirdness as well, now it works with the `folder_path_for_exe` as the first argument of the script , which is the destination folder specified. 

Committing that: 

```
    if platform.system() == "Darwin":
        source_path = "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"
        destination_path =  os.path.abspath(folder_path_for_exe) + "/Google Chrome"
        source_path = source_path.replace('\\', '')
        shutil.copy(source_path, destination_path)
        executable_path = destination_path
    else:
        executable_path = os.path.join(folder_path_for_exe, "chromedriver.exe")
```

**Comment by hansalemaos** [comment]
Perfect! Thank you very much! Windows is still working fine, I am going to update package for PIP now!

**Pull request merged**
